---
engines:
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths:
  - features/
  - vendor/
engines:
  govet:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: true

ratings:
  paths:
    - "**.go"
