language: go

go:
  - 1.7

before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

install:
  - go get github.com/Masterminds/glide
  - glide install
  - go install


script:
  # - |-
  #   touch ./coverage.tmp && echo 'mode: atomic' > coverage.txt && go list ./... | grep -v /vendor | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp -coverpkg $(go list ./... | grep -v /vendor | tr "\n" ",") {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp
  # - goveralls -coverprofile="coverage.txt"
  # - go test -race $(go list ./... | grep -v /vendor | grep -v /cmd)
  # - go test -v -bench=.* -run=none $(glide novendor)
  - go test


after_success:
  - bin/build_on_travis

deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true


notifications:
  email: false
